 services:
  mysql:
    image: mysql:8.0
    container_name: fleet_mysql
    restart: always
    env_file:
      - fleet.env
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  fleet:
    image: fleetdm/fleet:latest
    container_name: fleet_server
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    command: fleet prepare db --no-prompt --mysql_address=mysql:3306 --mysql_username=$MYSQL_USER --mysql_password=$MYSQL_PASSWORD --mysql_database=$MYSQL_DATABASE && fleet serve
    environment:
      FLEET_MYSQL_ADDRESS: mysql:3306
      FLEET_MYSQL_USERNAME: $MYSQL_USER
      FLEET_MYSQL_PASSWORD: $MYSQL_PASSWORD
      FLEET_MYSQL_DATABASE: $MYSQL_DATABASE
      FLEET_SERVER_ADDRESS: 0.0.0.0:8080

volumes:
  mysql_data:
