  fleet:
    image: fleetdm/fleet:v4.40.0
    platform: linux/amd64
    container_name: fleet_server
    restart: always
    depends_on:
      - prepare-db
      - mysql
      - redis
    ports:
      - "8080:8080"
    command: fleet serve
    environment:
      FLEET_MYSQL_ADDRESS: mysql:3306
      FLEET_MYSQL_USERNAME: fleet
      FLEET_MYSQL_PASSWORD: fleetpass
      FLEET_MYSQL_DATABASE: fleet
      FLEET_REDIS_ADDRESS: redis:6379
      FLEET_SERVER_ADDRESS: 0.0.0.0:8080
      FLEET_SERVER_TLS: false
